### ISSUE TITLE
Error: not found: npm

### ISSUE THREAD

**Issue by AdriVanHoudt** [zaggino/brackets-eslint#18]
```js
[node-error 8:47:20 PM] Error: not found: npm
    at F (/Users/adri/Library/Application Support/Brackets/extensions/user/brackets-eslint/node_modules/enable-global-packages/node_modules/find-global-packages/node_modules/which/which.js:72:28)
    at E (/Users/adri/Library/Application Support/Brackets/extensions/user/brackets-eslint/node_modules/enable-global-packages/node_modules/find-global-packages/node_modules/which/which.js:75:29)
    at /Users/adri/Library/Application Support/Brackets/extensions/user/brackets-eslint/node_modules/enable-global-packages/node_modules/find-global-packages/node_modules/which/which.js:83:16
    at Object.oncomplete (fs.js:107:15)NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
```

Also I get this but not sure if related
```js
[CodeInspection] Provider ESLint (async) failed: cleanup/language/CodeInspection.js:262 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)main.js:62 (anonymous function)thirdparty.min.js:559 (anonymous function)thirdparty.min.js:559 jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559 e.(anonymous function)/utils/NodeConnection.js:230 (anonymous function)/utils/NodeConnection.js:229 NodeConnection._cleanup/utils/NodeConnection.js:327 NodeConnection.connect/utils/NodeConnection.js:266 self._ws.onclose
```

And the global packages are not working for me, on a mac now :/

**Comment by zaggino** [comment]
Can you try `which npm` from the console please?

**Comment by AdriVanHoudt** [comment]
`/usr/local/bin/npm`

running just `npm` returns 
`npm@2.13.1 /usr/local/lib/node_modules/npm` (last line)

**Comment by zaggino** [comment]
Ok, thanks, I'll check what's the issue today.

**Comment by zaggino** [comment]
@AdriVanHoudt can you try installing `0.24.2`? just updated

**Comment by AdriVanHoudt** [comment]
@zaggino seems to work at first glance, what changed?

**Comment by zaggino** [comment]
seems that for some reason, when you launch node through brackets, `/usr/local/bin` is not in the `PATH` env variable ... my best guess the node within brackets is running under a different user or with some different permissions?

https://github.com/zaggino/enable-global-packages/blob/master/index.js#L10-L17

**Comment by AdriVanHoudt** [comment]
Nice thanks, I will close this because it looks fixed, if it comes up again I will reopen again.
