### ISSUE TITLE
Problem with configuring eslint

### ISSUE THREAD

**Issue by toxicbeaver** [zaggino/brackets-eslint#41]
Hello

I have a problem with configuring eslint in Brackets. It doesn't matter where I put my .eslintrc file (either \Brackets\extensions\user\brackets-eslint or the project folder) I always get an error in gutter:

`ESLint terminated with error: ENOENT, no such file or directory`

Console log in F12 throws this error:

`[CodeInspection] Provider ESLint (async) failed: ENOENT, no such file or directory`

My specs:
Win 7 x64
node v. 6.2.1
npm v. 3.9.3
Brackets v. 1.7.0.-16898
brackets-eslint v. 2.9.1
eslint v. 3.2.2

Any help would be appreciated.
Thanks in advance.

**Comment by zaggino** [comment]
Released `2.9.2`, can you please try to reinstall, close and re-open brackets and let me know if it fixes the problem?

**Comment by zaggino** [comment]
Hi, with `2.9.5` when you open the brackets console (F12 or Debug->Show developer tools) you should see more information about the error. Look for anything that mentions `brackets-eslint` and paste it here.

**Comment by ReyPena** [comment]
I have the same error #43 the output is:
```
[CodeInspection] Provider ESLint (async) failed: ENOENT, no such file or directory /language/CodeInspection.js:278
(anonymous function)
```

**Comment by zaggino** [comment]
Is there anything before the line `[CodeInspection] Provider ESLint (async) failed` ?

**Comment by ReyPena** [comment]
I'm using a this: https://launchpad.net/~webupd8team/+archive/ubuntu/brackets
This is all the dev-tools show:

```
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:560:24) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:467:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:405)
    at file:///home/rey/.config/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:48:9
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:55:7) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:467:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:405)
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:430:9) /utils/DeprecationWarning.js:90
Fail to nomalize Cmd-Shift-] /command/KeyBindingManager.js:580
Fail to nomalize Cmd-Shift-[ /command/KeyBindingManager.js:580
NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
Error while loading extensions: 
Error
get stack: function () { [native code] }
message: "Paths must be absolute: 'ho'"
set stack: function () { [native code] }
__proto__: d
 main.js:128
loadExtensions main.js:128
Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp /command/KeyBindingManager.js:749
_addBinding /command/KeyBindingManager.js:749
Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown /command/KeyBindingManager.js:749
_addBinding /command/KeyBindingManager.js:749
Exception when calling a 'brackets done loading' handler: TypeError: Cannot call method 'exists' of undefined /utils/AppInit.js:95
_callHandler /utils/AppInit.js:95
TypeError: Cannot call method 'exists' of undefined
    at loadExtensions (file:///home/rey/.config/Brackets/extensions/user/brackets-emmet/main.js:131:8)
    at file:///home/rey/.config/Brackets/extensions/user/brackets-emmet/main.js:266:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:303:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27220)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28096)
    at Object.eval (/brackets.js:301:30)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724)
    at Object.e.(anonymous function) (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28704)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28280)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724)
    at Object.e.(anonymous function) [as resolve] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28704) /utils/AppInit.js:96
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:422:18
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:303:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27220)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28096)
    at Object.eval (/brackets.js:301:30)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724)
    at Object.e.(anonymous function) (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28704)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28280)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at renderTools (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:313:10)
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:423:12
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:303:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27220)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28096)
    at Object.eval (/brackets.js:301:30)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724)
    at Object.e.(anonymous function) (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28704)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:28280)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at printTodo (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:183:18)
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:335:4)
    at Object.publish (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/Events.js:16:21)
    at setTodos (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:175:10)
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:327:4)
    at Object.publish (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/Events.js:16:21)
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/SettingsManager.js:61:11
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/SettingsManager.js:89:5
    at File.eval (/filesystem/FileSystemEntry.js:301:13)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:263:21)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:232:17)
    at appshell:273:13 /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at renderTodo (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:253:21)
    at printTodo (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:184:12)
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:335:4)
    at Object.publish (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/Events.js:16:21)
    at setTodos (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:175:10)
    at Object.<anonymous> (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:327:4)
    at Object.publish (file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/Events.js:16:21)
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/SettingsManager.js:61:11
    at file:///home/rey/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/modules/SettingsManager.js:89:5
    at File.eval (/filesystem/FileSystemEntry.js:301:13)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:263:21)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:232:17)
    at appshell:273:13 /utils/DeprecationWarning.js:90
[CodeInspection] Provider ESLint (async) failed: ENOENT, no such file or directory /language/CodeInspection.js:278
(anonymous function)
```

**Comment by zaggino** [comment]
Seems like `brackets-emmet` extension is broken, have you tried removing it?

**Comment by GusGF** [comment]
Getting this ESLint problem "ESLint terminated with error: ENOENT, no such file or directory". I am new to Javascript and only getting the hang of Brackets. Have copied the extract below from the console.

[CodeInspection] Provider ESLint (async) failed: ENOENT, no such file or directory(anonymous function) @ /language/CodeInspection.js:278

console.error("[CodeInspection] Provider " + provider.name + " (async) failed: " + err);

**Comment by zaggino** [comment]
@GusGF try again with version `2.9.7` please.

**Comment by GusGF** [comment]
Absolutely made no difference still getting the same error :(

**Comment by zaggino** [comment]
Can any of you guys give me a project to clone that replicates this issue?

**Comment by GusGF** [comment]
I've done up a simple Brackets project which I can send to you.

**Comment by zaggino** [comment]
zaggino at gmail, thx

**Comment by zaggino** [comment]
Updated to `2.9.8`, please provide exact copy-paste from error console, I'm shooting blind here but I've updated the error logging.

**Comment by guess-and-correct** [comment]
Looks like something different got broken. Drawer notification:
`ESLint zakończył z błędem: TypeError: Cannot call method 'executeOnText' of undefined`

Console output:
`NodeDebugUtils.js:114 [node-error 5:03:02 PM] [brackets-eslint] { [Error: Cannot find module 'escope'] code: 'MODULE_NOT_FOUND' }handleLogEvent @ NodeDebugUtils.js:114
NodeDebugUtils.js:114 [node-error 5:03:02 PM] [brackets-eslint] Error thrown in executeOnText: TypeError: Cannot call method 'executeOnText' of undefined
  at C:\Users\Karol\AppData\Roaming\Brackets\extensions\user\brackets-eslint\dist\node\eslint.js:209:23
  at fs.js:266:14
  at C:\Users\Karol\AppData\Roaming\Brackets\extensions\user\brackets-sass-lint\node_modules\sass-lint\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:43:10
  at Object.oncomplete (fs.js:107:15)
handleLogEvent @ NodeDebugUtils.js:114
/language/CodeInspection.js:278 [CodeInspection] Provider ESLint (async) failed: TypeError: Cannot call method 'executeOnText' of undefined(anonymous function) @ /language/CodeInspection.js:278
NodeDebugUtils.js:114 [node-error 5:03:04 PM] [brackets-eslint] { [Error: Cannot find module 'escope'] code: 'MODULE_NOT_FOUND' }handleLogEvent @ NodeDebugUtils.js:114`

**Comment by GusGF** [comment]
I've taken a screen print for you, let me know if this isn't enough.

I haven't updated yet as I've seen there is a message from Karol regarding
something else not working.

Should I still go ahead and update to 2.9.8?

Regards
Fergus

**Comment by zaggino** [comment]
Thanks guys `2.9.10` released. Added a bit more information into the logging.
`Cannot call method 'executeOnText' of undefined` means that `eslint` wasn't able to load properly. Please try `2.9.10` and let me know how the console errors look now.

**Comment by guess-and-correct** [comment]
It works! Thank you.

**Comment by GusGF** [comment]
BY GEORGE!! I do believe that's worked, well done kind sir :)

**Comment by zaggino** [comment]
:beers:
